#include <iostream>
#include <string>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include "button.h"
#include "texture.h"
void PVE(int);
void PVE1(int);
void PVE2(int);
void PVE3(int);
void PVEScrolling(int);
void PVEchoosecharacter(int);
void PVE_tutorial_start();
void PVE_tutorial();
