#include <iostream>
#include <string>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include "button.h"
#include "texture.h"
void PVE();
void PVE1();
void PVE2();
void PVE3();
//void PVEScrolling(int);
//void PVEchoosecharacter();
//void PVE_tutorial_start();
//void PVE_tutorial();
