#include <iostream>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include "button.h"
#include "texture.h"
void PVP(int);
void PVP1(int);
void PVP2(int);
void PVP3(int);
void PVPScrolling(int);
void PVPchoosecharacter(int);
void PVP_tutorial_start();
void PVP_tutorial();