#include <iostream>
#include <SDL.h>
#include <SDL_image.h>
#include <SDL_ttf.h>
#include "button.h"
#include "texture.h"
void PVP();
void PVP1();
void PVP2();
void PVP3();
//void PVPScrolling(int);
//void PVPchoosecharacter();
//void PVP_tutorial_start();
//void PVP_tutorial();